name: Build iOS/Mac

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build libvlc
        run: |
          git clone https://code.videolan.org/videolan/vlc && cd vlc
          mkdir build && cd build
          ../extras/package/macosx/build.sh ${ARGS} -a ${ARCH}

      - name: Build unity plugin
        run: |
          cd vlc/build/macos-install
          sed -i '' "1s|.*|prefix=$(pwd | sed 's#/#\\\/#g')|" lib/pkgconfig/libvlc.pc
          export PATH="$HOME/sandbox/bin:$PATH"
          cd ../../..
          PKG_CONFIG_PATH=./vlc/build/macos-install/lib/pkgconfig meson setup build_${ARCH} ${ARGS_TRIAL} --buildtype release
          ninja -C build_${ARCH}
          mv "build_${ARCH}/PluginSource/libVLCUnityPlugin.1.dylib" "build_${ARCH}/PluginSource/libVLCUnityPlugin.dylib"
          install_name_tool -add_rpath @loader_path/ build_${ARCH}/PluginSource/libVLCUnityPlugin.dylib

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: production-artifacts
          path: |
            build_${ARCH}/PluginSource/libVLCUnityPlugin.dylib
